/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConversarRouteImport } from './routes/conversar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SankhyaIndexRouteImport } from './routes/sankhya/index'
import { Route as SankhyaStartGameRouteImport } from './routes/sankhya/startGame'

const ConversarRoute = ConversarRouteImport.update({
  id: '/conversar',
  path: '/conversar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SankhyaIndexRoute = SankhyaIndexRouteImport.update({
  id: '/sankhya/',
  path: '/sankhya/',
  getParentRoute: () => rootRouteImport,
} as any)
const SankhyaStartGameRoute = SankhyaStartGameRouteImport.update({
  id: '/sankhya/startGame',
  path: '/sankhya/startGame',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conversar': typeof ConversarRoute
  '/sankhya/startGame': typeof SankhyaStartGameRoute
  '/sankhya/': typeof SankhyaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conversar': typeof ConversarRoute
  '/sankhya/startGame': typeof SankhyaStartGameRoute
  '/sankhya': typeof SankhyaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conversar': typeof ConversarRoute
  '/sankhya/startGame': typeof SankhyaStartGameRoute
  '/sankhya/': typeof SankhyaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/conversar' | '/sankhya/startGame' | '/sankhya/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/conversar' | '/sankhya/startGame' | '/sankhya'
  id: '__root__' | '/' | '/conversar' | '/sankhya/startGame' | '/sankhya/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConversarRoute: typeof ConversarRoute
  SankhyaStartGameRoute: typeof SankhyaStartGameRoute
  SankhyaIndexRoute: typeof SankhyaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/conversar': {
      id: '/conversar'
      path: '/conversar'
      fullPath: '/conversar'
      preLoaderRoute: typeof ConversarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sankhya/': {
      id: '/sankhya/'
      path: '/sankhya'
      fullPath: '/sankhya/'
      preLoaderRoute: typeof SankhyaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sankhya/startGame': {
      id: '/sankhya/startGame'
      path: '/sankhya/startGame'
      fullPath: '/sankhya/startGame'
      preLoaderRoute: typeof SankhyaStartGameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConversarRoute: ConversarRoute,
  SankhyaStartGameRoute: SankhyaStartGameRoute,
  SankhyaIndexRoute: SankhyaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
